import { EditorView } from "@codemirror/view";
import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { tags as t } from "@lezer/highlight";
import type { Extension } from "@codemirror/state";

/**
 * CodeMirror theme wired to Judgify's Material design tokens.
 *
 * Colors reference the CSS custom properties generated by Tailwind's `@theme`
 * block (see src/index.css), so the editor tracks the design system.
 */
export const judgifyTheme = EditorView.theme(
  {
    "&": {
      color: "var(--color-on-surface)",
      backgroundColor: "var(--color-surface-container-lowest)",
      height: "100%",
      fontSize: "var(--text-code-md, 0.875rem)",
    },
    ".cm-scroller": {
      fontFamily: "var(--font-jetbrains-mono, monospace)",
      lineHeight: "1.5rem",
      paddingTop: "0.5rem",
    },
    ".cm-content": {
      caretColor: "var(--color-primary)",
    },
    "&.cm-focused": {
      outline: "none",
    },
    ".cm-cursor, .cm-dropCursor": {
      borderLeftColor: "var(--color-primary)",
    },
    "&.cm-focused .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection":
      {
        backgroundColor: "color-mix(in srgb, var(--color-primary) 22%, transparent)",
      },
    ".cm-activeLine": {
      backgroundColor: "color-mix(in srgb, var(--color-primary) 7%, transparent)",
    },
    ".cm-gutters": {
      backgroundColor: "var(--color-surface-container-lowest)",
      color: "var(--color-outline-variant)",
      border: "none",
      borderRight: "1px solid color-mix(in srgb, var(--color-outline-variant) 10%, transparent)",
    },
    ".cm-activeLineGutter": {
      backgroundColor: "transparent",
      color: "var(--color-on-surface-variant)",
    },
    ".cm-lineNumbers .cm-gutterElement": {
      padding: "0 0.75rem 0 1rem",
    },
    ".cm-matchingBracket, &.cm-focused .cm-matchingBracket": {
      backgroundColor: "color-mix(in srgb, var(--color-primary) 25%, transparent)",
      color: "inherit",
      outline: "1px solid color-mix(in srgb, var(--color-primary) 45%, transparent)",
    },
    ".cm-selectionMatch": {
      backgroundColor: "color-mix(in srgb, var(--color-primary) 14%, transparent)",
    },
    ".cm-tooltip": {
      backgroundColor: "var(--color-surface-container-high)",
      border: "1px solid var(--color-outline-variant)",
      borderRadius: "0.5rem",
      color: "var(--color-on-surface)",
    },
    ".cm-tooltip-autocomplete ul li[aria-selected]": {
      backgroundColor: "color-mix(in srgb, var(--color-primary) 20%, transparent)",
      color: "var(--color-on-surface)",
    },
  },
  { dark: true },
);

/**
 * Token colors drawn from the app palette so highlighting feels native:
 * cool purple keywords, primary-blue functions, green strings, amber numbers,
 * cyan types, and muted comments.
 */
const judgifyHighlight = HighlightStyle.define([
  { tag: [t.comment, t.lineComment, t.blockComment, t.docComment], color: "#8c909f", fontStyle: "italic" },
  { tag: [t.keyword, t.controlKeyword, t.moduleKeyword, t.operatorKeyword, t.definitionKeyword], color: "#d0bcff" },
  { tag: [t.string, t.special(t.string), t.character], color: "#4edea3" },
  { tag: t.escape, color: "#ffb4ab" },
  { tag: [t.number, t.integer, t.float], color: "#ffb347" },
  { tag: [t.bool, t.null, t.atom, t.constant(t.variableName)], color: "#ffb347" },
  { tag: [t.function(t.variableName), t.function(t.propertyName)], color: "#adc6ff" },
  { tag: [t.typeName, t.className, t.namespace], color: "#82d4ff" },
  { tag: t.propertyName, color: "#c2c6d6" },
  { tag: t.variableName, color: "var(--color-on-surface)" },
  { tag: [t.self, t.labelName], color: "#ffb4ab" },
  { tag: [t.meta, t.annotation], color: "#ffb347" },
  { tag: [t.operator, t.punctuation, t.bracket, t.separator], color: "#c2c6d6" },
  { tag: t.invalid, color: "var(--color-error)" },
]);

/** Syntax highlighting extension for the Judgify editor. */
export const judgifyHighlighting: Extension = syntaxHighlighting(judgifyHighlight);
